# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-09-02 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrash_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysInfo',
            fields=[
                ('kname', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='键名')),
                ('kvalue', models.CharField(max_length=20, verbose_name='值')),
            ],
            options={
                'verbose_name': '系统信息',
                'verbose_name_plural': '系统信息',
            },
        ),
    ]
