# Generated by Django 2.2.4 on 2019-09-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrash_manage', '0003_auto_20190904_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleTrash',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='垃圾名')),
            ],
        ),
        migrations.CreateModel(
            name='DryTrash',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='垃圾名')),
            ],
        ),
        migrations.CreateModel(
            name='HarmTrash',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='垃圾名')),
            ],
        ),
        migrations.CreateModel(
            name='WetTrash',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='垃圾名')),
            ],
        ),
    ]
