# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-27 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itrash_manage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picinfo',
            name='path',
        ),
        migrations.AddField(
            model_name='picinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trashimg', verbose_name='图像'),
        ),
        migrations.AddField(
            model_name='picinfo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='thumb_trashimg', verbose_name='缩略图'),
        ),
    ]
